In [1]:
import h5py
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np
import pandas as pd

In [31]:
folder_path = './DATASET' # Replace with your folder path
# This creates a list of extensions (including the dot)
file_paths = [f for f in Path(folder_path).iterdir() if f.is_file() and f.suffix == '.hdf5']

df = None
data = []
for idx, file in enumerate(file_paths):
    layer_dict = {}
    file_info = h5py.File(file, 'r')
    file_data = file_info['OpenData']
    x = file_data[0]
    y = file_data[1]
    p = file_data[5]
    ir = file_data[6]
    c1 = file_data[9]
    c2 = file_data[10]
    id1 = file_data[7]
    id2 = file_data[8]

    # print(file, np.unique(id1, return_counts=True), np.unique(id2, return_counts=True))
    
    layer_dict["file"] = file
    layer_dict["num_points"] = len(x)
    layer_dict["bulk_indicator"] = True if int(id1[0])== 1 else False
    layer_dict["first_3_post_anomaly"] = True if int(id2[0])!= 0 else False
    layer_dict["min_x"] = x.min()
    layer_dict["max_x"] = x.max()
    layer_dict["min_y"] = y.min()
    layer_dict["max_y"] = y.max()
    layer_dict["bulk_id"] = id1[0]
    layer_dict["ooc_id"] = id2[0]
    layer_dict["xa"] = -1
    layer_dict["xb"] = -1
    layer_dict["xc"] = -1
    layer_dict["xd"] = -1
    layer_dict["ya"] = -1
    layer_dict["yb"] = -1
    layer_dict["yc"] = -1
    layer_dict["yd"] = -1

    # x_mid = (x.min() + x.max())/2
    # y_mid = (y.min() + y.max())/2

    if len(x) < 10000:
        # print(file)
        ys_for_center_xs = y[(-26 < x) & (x < -20)]
        mid_y = (ys_for_center_xs.max() + ys_for_center_xs.min())/2
        # print("mid_y", mid_y)
        top_for_center_xs = ys_for_center_xs[ys_for_center_xs > mid_y] 
        ya = top_for_center_xs.max()
        yb = top_for_center_xs.min()
        bottom_for_center_xs = ys_for_center_xs[ys_for_center_xs < mid_y]
        yc = bottom_for_center_xs.max()
        yd = bottom_for_center_xs.min()
        
        xs_for_center_ys = x[(-88 < y) & (y < -82)]
        mid_x = (xs_for_center_ys.max() + xs_for_center_ys.min())/2
        # print("mid_x", mid_x)
        left_for_center_ys = xs_for_center_ys[xs_for_center_ys < mid_x]
        xa = left_for_center_ys.min()
        xb = left_for_center_ys.max()
        right_for_center_ys = xs_for_center_ys[xs_for_center_ys > mid_x]
        xc = right_for_center_ys.min()
        xd = right_for_center_ys.max()

        # print("xa", xa)
        # print("xb", xb)
        # print("xc", xc)
        # print("xd", xd)
        # print()
        # print("ya", ya)
        # print("yb", yb)
        # print("yc", yc)
        # print("yd", yd)
        # break

        layer_dict["xa"] = xa
        layer_dict["xb"] = xb
        layer_dict["xc"] = xc
        layer_dict["xd"] = xd
        layer_dict["ya"] = ya
        layer_dict["yb"] = yb
        layer_dict["yc"] = yc
        layer_dict["yd"] = yd

    

    if not isinstance(df, pd.DataFrame):
        df = pd.DataFrame(layer_dict, index=[idx])
    else:
        df = pd.concat([df, pd.DataFrame(layer_dict, index=[idx])])

In [32]:
display(df)

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y,bulk_id,ooc_id,xa,xb,xc,xd,ya,yb,yc,yd
0,DATASET/layer331.hdf5,31100,True,False,-27.762575,-18.462799,-89.484657,-80.172905,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
1,DATASET/layer108.hdf5,30731,True,False,-27.765194,-18.462425,-89.482407,-80.173653,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
2,DATASET/layer151.hdf5,31087,True,False,-27.762199,-18.463549,-89.485031,-80.172531,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
3,DATASET/layer155.hdf5,30839,True,False,-27.764446,-18.463173,-89.482407,-80.172531,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
4,DATASET/layer209.hdf5,31133,True,False,-27.767815,-18.456062,-89.481293,-80.172905,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374,DATASET/layer84.hdf5,31114,True,False,-27.761826,-18.463173,-89.483154,-80.172531,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
375,DATASET/layer157.hdf5,9679,False,False,-27.765194,-18.459057,-89.482040,-80.177399,0.0,0.0,-27.764446,-26.987125,-19.239372,-18.459805,-80.177399,-80.954712,-88.694237,-89.48204
376,DATASET/layer142.hdf5,30511,True,False,-27.767441,-18.458309,-89.480911,-80.174400,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
377,DATASET/layer244.hdf5,30704,True,False,-27.765944,-18.458309,-89.481293,-80.174026,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000
378,DATASET/layer189.hdf5,30978,True,False,-27.764446,-18.461302,-89.482407,-80.174774,1.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.00000

In [44]:
xas = df["xa"]
xbs = df["xb"]
xcs = df["xc"]
xds = df["xd"]
yas = df["ya"]
ybs = df["yb"]
ycs = df["yc"]
yds = df["yd"]

xas_min = xas[xas != -1].min()
xas_max = xas[xas != -1].max()

xbs_min = xbs[xbs != -1].min()
xbs_max = xbs[xbs != -1].max()

xcs_min = xcs[xcs != -1].min()
xcs_max = xcs[xcs != -1].max()

xds_min = xds[xds != -1].min()
xds_max = xds[xds != -1].max()


# xas_min, xas_max
# xbs_min, xbs_max
# xcs_min, xcs_max
# xds_min, xds_max


yas_min = yas[yas != -1].min()
yas_max = yas[yas != -1].max()

ybs_min = ybs[ybs != -1].min()
ybs_max = ybs[ybs != -1].max()

ycs_min = ycs[ycs != -1].min()
ycs_max = ycs[ycs != -1].max()

yds_min = yds[yds != -1].min()
yds_max = yds[yds != -1].max()


# yas_min, yas_max
# ybs_min, ybs_max
# ycs_min, ycs_max
# yds_min, yds_max

# xas_max, xbs_min, xcs_max, xds_min, yas_min, ybs_max, ycs_min, yds_max
xbs_max, xcs_min, ybs_min, ycs_max

(-26.98001480102539,
 -19.24423599243164,
 -80.96295166015625,
 -88.69274139404297)

In [17]:
not_bulk = df[df["bulk_indicator"]==False]
bulk = df[df["bulk_indicator"]==True]
not_bulk

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y,bulk_id,ooc_id
5,DATASET/layer272.hdf5,9720,False,False,-27.766317,-18.459431,-89.481293,-80.174400,0.0,0.0
16,DATASET/layer91.hdf5,9617,False,False,-27.764446,-18.463173,-89.485031,-80.172905,0.0,0.0
20,DATASET/layer306.hdf5,9641,False,False,-27.764446,-18.464670,-89.482407,-80.172531,0.0,0.0
21,DATASET/layer94.hdf5,31062,False,True,-27.763699,-18.463173,-89.483902,-80.172905,0.0,2.0
23,DATASET/layer305.hdf5,9707,False,False,-27.770809,-18.459431,-89.482040,-80.172905,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
355,DATASET/layer62.hdf5,30770,False,True,-27.764446,-18.461678,-89.483154,-80.174026,0.0,1.0
356,DATASET/layer90.hdf5,9672,False,False,-27.771931,-18.458683,-89.484283,-80.173279,0.0,0.0
360,DATASET/layer26.hdf5,9670,False,False,-27.770435,-18.458309,-89.482788,-80.174026,0.0,0.0
372,DATASET/layer308.hdf5,9560,False,False,-27.695583,-18.565344,-89.480537,-80.175148,0.0,0.0
375,DATASET/layer157.hdf5,9679,False,False,-27.765194,-18.459057,-89.482040,-80.177399,0.0,0.0

In [24]:
bulk

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y,bulk_id,ooc_id
0,DATASET/layer331.hdf5,31100,True,False,-27.762575,-18.462799,-89.484657,-80.172905,1.0,0.0
1,DATASET/layer108.hdf5,30731,True,False,-27.765194,-18.462425,-89.482407,-80.173653,1.0,0.0
2,DATASET/layer151.hdf5,31087,True,False,-27.762199,-18.463549,-89.485031,-80.172531,1.0,0.0
3,DATASET/layer155.hdf5,30839,True,False,-27.764446,-18.463173,-89.482407,-80.172531,1.0,0.0
4,DATASET/layer209.hdf5,31133,True,False,-27.767815,-18.456062,-89.481293,-80.172905,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
373,DATASET/layer239.hdf5,30898,True,False,-27.763325,-18.463173,-89.483154,-80.173279,1.0,0.0
374,DATASET/layer84.hdf5,31114,True,False,-27.761826,-18.463173,-89.483154,-80.172531,1.0,0.0
376,DATASET/layer142.hdf5,30511,True,False,-27.767441,-18.458309,-89.480911,-80.174400,1.0,0.0
377,DATASET/layer244.hdf5,30704,True,False,-27.765944,-18.458309,-89.481293,-80.174026,1.0,0.0
378,DATASET/layer189.hdf5,30978,True,False,-27.764446,-18.461302,-89.482407,-80.174774,1.0,0.0

In [20]:
a = not_bulk[not_bulk["first_3_post_anomaly"]==True]
print(len(a))
a

27

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y,bulk_id,ooc_id
21,DATASET/layer94.hdf5,31062,False,True,-27.763699,-18.463173,-89.483902,-80.172905,0.0,2.0
30,DATASET/layer200.hdf5,30644,False,True,-27.762575,-18.460928,-89.481293,-80.172905,0.0,5.0
31,DATASET/layer314.hdf5,30895,False,True,-27.764446,-18.460928,-89.482788,-80.173653,0.0,8.0
43,DATASET/layer352.hdf5,31081,False,True,-27.761452,-18.463173,-89.483902,-80.172905,0.0,9.0
50,DATASET/layer199.hdf5,30886,False,True,-27.770061,-18.457935,-89.481293,-80.172531,0.0,5.0
65,DATASET/layer164.hdf5,31046,False,True,-27.765194,-18.460180,-89.481293,-80.174400,0.0,4.0
74,DATASET/layer274.hdf5,30483,False,True,-27.764072,-18.462425,-89.481659,-80.173279,0.0,7.0
90,DATASET/layer313.hdf5,30968,False,True,-27.764072,-18.462799,-89.482788,-80.172157,0.0,8.0
96,DATASET/layer129.hdf5,30569,False,True,-27.764446,-18.460180,-89.482040,-80.173279,0.0,3.0
97,DATASET/layer61.hdf5,30555,False,True,-27.767815,-18.458309,-89.481659,-80.174774,0.0,1.0
115,DATASET/layer275.hdf5,30744,False,True,-27.763699,-18.463173,-89.481659,-80.173279,0.0,7.0
118,DATASET/layer162.hdf5,31073,False,True,-27.764446,-18.463173,-89.482788,-80.172905,0.0,4.0
121,DATASET/layer273.hdf5,30994,False,True,-27.769312,-18.457935,-89.481293,-80.175522,0.0,7.0
161,DATASET/layer235.hdf5,30913,False,True,-27.767441,-18.459057,-89.482040,-80.171402,0.0,6.0
173,DATASET/layer236.hdf5,30864,False,True,-27.762949,-18.463923,-89.482407,-80.172157,0.0,6.0
180,DATASET/layer237.hdf5,30689,False,True,-27.767067,-18.459805,-89.480911,-80.174026,0.0,6.0
197,DATASET/layer128.hdf5,30534,False,True,-27.603519,-18.474775,-89.480911,-80.174774,0.0,3.0
201,DATASET/layer198.hdf5,30714,False,True,-27.766317,-18.457935,-89.481293,-80.173653,0.0,5.0
241,DATASET/layer60.hdf5,31013,False,True,-27.763325,-18.457560,-89.482407,-80.173653,0.0,1.0
249,DATASET/layer93.hdf5,30662,False,True,-27.767067,-18.458683,-89.481659,-80.174400,0.0,2.0
266,DATASET/layer95.hdf5,30906,False,True,-27.764446,-18.463549,-89.482040,-80.172531,0.0,2.0
278,DATASET/layer163.hdf5,30760,False,True,-27.769686,-18.458683,-89.480911,-80.174774,0.0,4.0
286,DATASET/layer353.hdf5,30780,False,True,-27.766317,-18.460928,-89.482407,-80.174026,0.0,9.0
310,DATASET/layer127.hdf5,30979,False,True,-27.765944,-18.462051,-89.484657,-80.173279,0.0,3.0
336,DATASET/layer312.hdf5,30827,False,True,-27.766317,-18.459805,-89.482407,-80.174774,0.0,8.0
351,DATASET/layer354.hdf5,31102,False,True,-27.767441,-18.457186,-89.480911,-80.175148,0.0,9.0
355,DATASET/layer62.hdf5,30770,False,True,-27.764446,-18.461678,-89.483154,-80.174026,0.0,1.0

In [21]:
b = not_bulk[not_bulk["first_3_post_anomaly"]==False]
print(len(b))
b

55

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y,bulk_id,ooc_id
5,DATASET/layer272.hdf5,9720,False,False,-27.766317,-18.459431,-89.481293,-80.174400,0.0,0.0
16,DATASET/layer91.hdf5,9617,False,False,-27.764446,-18.463173,-89.485031,-80.172905,0.0,0.0
20,DATASET/layer306.hdf5,9641,False,False,-27.764446,-18.464670,-89.482407,-80.172531,0.0,0.0
23,DATASET/layer305.hdf5,9707,False,False,-27.770809,-18.459431,-89.482040,-80.172905,0.0,0.0
26,DATASET/layer231.hdf5,9687,False,False,-27.769312,-18.459057,-89.481293,-80.173279,0.0,0.0
28,DATASET/layer304.hdf5,9696,False,False,-27.765568,-18.457560,-89.482407,-80.178146,0.0,0.0
33,DATASET/layer229.hdf5,9690,False,False,-27.764820,-18.463549,-89.481659,-80.172531,0.0,0.0
34,DATASET/layer126.hdf5,9646,False,False,-27.765194,-18.462425,-89.482407,-80.173279,0.0,0.0
37,DATASET/layer266.hdf5,9677,False,False,-27.769312,-18.459431,-89.483536,-80.178146,0.0,0.0
39,DATASET/layer344.hdf5,9720,False,False,-27.764446,-18.457560,-89.482040,-80.173279,0.0,0.0
42,DATASET/layer309.hdf5,9678,False,False,-27.762949,-18.460554,-89.483154,-80.174400,0.0,0.0
67,DATASET/layer311.hdf5,9695,False,False,-27.766317,-18.457186,-89.482788,-80.172905,0.0,0.0
72,DATASET/layer267.hdf5,9675,False,False,-27.763699,-18.460928,-89.481659,-80.171402,0.0,0.0
77,DATASET/layer192.hdf5,9688,False,False,-27.765944,-18.459805,-89.482788,-80.173653,0.0,0.0
81,DATASET/layer265.hdf5,9666,False,False,-27.768188,-18.456062,-89.482407,-80.173653,0.0,0.0
95,DATASET/layer269.hdf5,9655,False,False,-27.768936,-18.458309,-89.481293,-80.174774,0.0,0.0
98,DATASET/layer303.hdf5,9642,False,False,-27.761826,-18.457935,-89.482407,-80.172531,0.0,0.0
117,DATASET/layer232.hdf5,9694,False,False,-27.762199,-18.463923,-89.483536,-80.173279,0.0,0.0
166,DATASET/layer271.hdf5,9687,False,False,-27.760704,-18.462051,-89.485031,-80.172905,0.0,0.0
170,DATASET/layer197.hdf5,9664,False,False,-27.763325,-18.462425,-89.482788,-80.172905,0.0,0.0
171,DATASET/layer268.hdf5,9689,False,False,-27.765194,-18.459431,-89.482407,-80.172905,0.0,0.0
178,DATASET/layer158.hdf5,9577,False,False,-27.764446,-18.464670,-89.353294,-80.225296,0.0,0.0
185,DATASET/layer161.hdf5,9706,False,False,-27.761826,-18.462051,-89.482407,-80.172157,0.0,0.0
186,DATASET/layer160.hdf5,9645,False,False,-27.767815,-18.458683,-89.484657,-80.175148,0.0,0.0
187,DATASET/layer310.hdf5,9619,False,False,-27.765568,-18.462425,-89.483154,-80.173279,0.0,0.0
195,DATASET/layer125.hdf5,9703,False,False,-27.769686,-18.459805,-89.482407,-80.174400,0.0,0.0
198,DATASET/layer195.hdf5,9663,False,False,-27.768936,-18.457560,-89.480911,-80.174774,0.0,0.0
204,DATASET/layer234.hdf5,9709,False,False,-27.767441,-18.456438,-89.476791,-80.175148,0.0,0.0
207,DATASET/layer196.hdf5,9668,False,False,-27.767067,-18.459057,-89.483902,-80.175522,0.0,0.0
211,DATASET/layer58.hdf5,9675,False,False,-27.765944,-18.459057,-89.482407,-80.174026,0.0,0.0
212,DATASET/layer345.hdf5,9652,False,False,-27.763325,-18.461678,-89.482788,-80.172531,0.0,0.0
215,DATASET/layer92.hdf5,9726,False,False,-27.764072,-18.459057,-89.481659,-80.175903,0.0,0.0
218,DATASET/layer159.hdf5,9689,False,False,-27.764446,-18.460554,-89.481293,-80.175522,0.0,0.0
220,DATASET/layer346.hdf5,9668,False,False,-27.765194,-18.460928,-89.480911,-80.177017,0.0,0.0
227,DATASET/layer347.hdf5,9650,False,False,-27.771557,-18.458309,-89.480164,-80.173653,0.0,0.0
232,DATASET/layer193.hdf5,9670,False,False,-27.762199,-18.465046,-89.483536,-80.172905,0.0,0.0
233,DATASET/layer351.hdf5,9687,False,False,-27.765944,-18.459431,-89.482407,-80.171783,0.0,0.0
236,DATASET/layer350.hdf5,9663,False,False,-27.766693,-18.457560,-89.482040,-80.174774,0.0,0.0
247,DATASET/layer348.hdf5,9691,False,False,-27.766317,-18.461302,-89.482788,-80.172531,0.0,0.0
251,DATASET/layer342.hdf5,9668,False,False,-27.761826,-18.463173,-89.483536,-80.172905,0.0,0.0
255,DATASET/layer349.hdf5,9677,False,False,-27.763325,-18.463923,-89.482788,-80.172531,0.0,0.0
274,DATASET/layer194.hdf5,9722,False,False,-27.762949,-18.460180,-89.482788,-80.173279,0.0,0.0
291,DATASET/layer343.hdf5,9662,False,False,-27.767441,-18.457560,-89.482788,-80.178513,0.0,0.0
307,DATASET/layer59.hdf5,9649,False,False,-27.761826,-18.461302,-89.482788,-80.172157,0.0,0.0
312,DATASET/layer230.hdf5,9673,False,False,-27.766693,-18.459057,-89.483154,-80.178513,0.0,0.0
333,DATASET/layer228.hdf5,9684,False,False,-27.764072,-18.462051,-89.482788,-80.174774,0.0,0.0
334,DATASET/layer270.hdf5,9683,False,False,-27.764446,-18.460180,-89.483154,-80.174400,0.0,0.0
342,DATASET/layer123.hdf5,9688,False,False,-27.762575,-18.461302,-89.481659,-80.172905,0.0,0.0
343,DATASET/layer307.hdf5,9689,False,False,-27.764072,-18.460554,-89.483902,-80.173653,0.0,0.0
348,DATASET/layer124.hdf5,9675,False,False,-27.765944,-18.456438,-89.482407,-80.174774,0.0,0.0
354,DATASET/layer233.hdf5,9723,False,False,-27.765568,-18.460554,-89.482040,-80.175148,0.0,0.0
356,DATASET/layer90.hdf5,9672,False,False,-27.771931,-18.458683,-89.484283,-80.173279,0.0,0.0
360,DATASET/layer26.hdf5,9670,False,False,-27.770435,-18.458309,-89.482788,-80.174026,0.0,0.0
372,DATASET/layer308.hdf5,9560,False,False,-27.695583,-18.565344,-89.480537,-80.175148,0.0,0.0
375,DATASET/layer157.hdf5,9679,False,False,-27.765194,-18.459057,-89.482040,-80.177399,0.0,0.0

In [22]:
c = bulk[bulk["first_3_post_anomaly"]==True]
print(len(c))
c

0

Empty DataFrame
Columns: [file, num_points, bulk_indicator, first_3_post_anomaly, min_x, max_x, min_y, max_y, bulk_id, ooc_id]
Index: []

In [23]:
d = bulk[bulk["first_3_post_anomaly"]==False]
print(len(d))
d

297

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y,bulk_id,ooc_id
0,DATASET/layer331.hdf5,31100,True,False,-27.762575,-18.462799,-89.484657,-80.172905,1.0,0.0
1,DATASET/layer108.hdf5,30731,True,False,-27.765194,-18.462425,-89.482407,-80.173653,1.0,0.0
2,DATASET/layer151.hdf5,31087,True,False,-27.762199,-18.463549,-89.485031,-80.172531,1.0,0.0
3,DATASET/layer155.hdf5,30839,True,False,-27.764446,-18.463173,-89.482407,-80.172531,1.0,0.0
4,DATASET/layer209.hdf5,31133,True,False,-27.767815,-18.456062,-89.481293,-80.172905,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
373,DATASET/layer239.hdf5,30898,True,False,-27.763325,-18.463173,-89.483154,-80.173279,1.0,0.0
374,DATASET/layer84.hdf5,31114,True,False,-27.761826,-18.463173,-89.483154,-80.172531,1.0,0.0
376,DATASET/layer142.hdf5,30511,True,False,-27.767441,-18.458309,-89.480911,-80.174400,1.0,0.0
377,DATASET/layer244.hdf5,30704,True,False,-27.765944,-18.458309,-89.481293,-80.174026,1.0,0.0
378,DATASET/layer189.hdf5,30978,True,False,-27.764446,-18.461302,-89.482407,-80.174774,1.0,0.0

In [25]:
np.unique(df["first_3_post_anomaly"], return_counts=True)

(array([False,  True]), array([352,  27]))

In [9]:
first_3 = df[df["first_3_post_anomaly"]==True]
first_3

,file,num_points,bulk_indicator,first_3_post_anomaly,min_x,max_x,min_y,max_y
97,DATASET/layer61.hdf5,30555,False,True,-27.767815,-18.458309,-89.481659,-80.174774
241,DATASET/layer60.hdf5,31013,False,True,-27.763325,-18.457560,-89.482407,-80.173653
355,DATASET/layer62.hdf5,30770,False,True,-27.764446,-18.461678,-89.483154,-80.174026

In [37]:
df["min_x"].round().unique()

array([-28.], dtype=float32)

In [ ]:
for i